pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                dir('Chapter07/sample5') {
                    sh 'chmod +x gradlew'
                    sh './gradlew test'
                }
            }
        }
    }
}
