pipeline {
    agent any

    stages {
        stage('Run JaCoCo Coverage Verification') {
            steps {
                sh './gradlew jacocoTestCoverageVerification'
            }
        }
    }
}
