// docker agent fix test
pipeline {
    agent {
        docker {
            image 'eclipse-temurin:8-jdk'
            args '-u root'
        }
    }

    triggers {
        pollSCM('* * * * *')
    }

    stages {
        stage('Compile') {
            steps {
                dir('Chapter08/sample1') {
                    sh 'chmod +x gradlew'
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit test') {
            steps {
                dir('Chapter08/sample1') {
                    sh './gradlew test'
                }
            }
        }

        stage('CodeCoverage') {
            when {
                changeset "**/*.java"
            }
            steps {
                dir('Chapter08/sample1') {
                    sh './gradlew jacocoTestReport jacocoTestCoverageVerification'
                }
            }
        }

        stage('Checkstyle') {
            when {
                changeset "**/*.java"
            }
            steps {
                dir('Chapter08/sample1') {
                    sh './gradlew checkstyleMain checkstyleTest'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Chapter08/sample1') {
                    sh './gradlew build'
                }
            }
        }
    }

    post {
        success {
            echo 'pipeline ran perfectly'
        }
        unsuccessful {
            echo 'pipeline failure'
        }
    }
}