pipeline {
    agent any

    stages {
        stage('Run JaCoCo Coverage Verification') {
            steps {
                dir('Chapter08/sample1') {
                    sh './gradlew jacocoTestCoverageVerification'
                }
            }
        }
    }
}